import type { Game, Rubric, VibeId } from "./types";
import { autoVibeTags } from "./vibes";

function r(
  luck: number,
  strategy: number,
  skill: number,
  social: number,
  complexity: number,
  replayability: number,
  resourceMgmt: number,
): Rubric {
  return { luck, strategy, skill, social, complexity, replayability, resourceMgmt };
}

type Raw = Omit<Game, "vibes"> & { vibes?: VibeId[] };

function g(raw: Raw): Game {
  const game: Game = { ...raw, vibes: raw.vibes ?? [] };
  const auto = autoVibeTags(game);
  const merged = Array.from(new Set([...(raw.vibes ?? []), ...auto]));
  return { ...game, vibes: merged };
}

const RAW: Raw[] = [
  {
    bggId: "178900",
    name: "Codenames",
    yearPublished: 2015,
    players: { min: 2, max: 8, best: [6, 7, 8] },
    playtime: { min: 15, max: 30, avg: 22 },
    age: { publisher: 14, community: 10 },
    rubric: r(40, 25, 50, 92, 22, 88, 8),
    mechanics: ["Team-Based Game", "Communication Limits", "Deduction"],
    categories: ["Party Game", "Word Game", "Spies / Secret Agents"],
    bggRating: 7.6,
    designer: "Vlaada Chvátil",
    description: "One-word clues. Two teams. Don't snipe the assassin.",
  },
  {
    bggId: "266192",
    name: "Wingspan",
    yearPublished: 2019,
    players: { min: 1, max: 5, best: [3, 4] },
    playtime: { min: 40, max: 70, avg: 55 },
    age: { publisher: 10, community: 8 },
    rubric: r(35, 70, 55, 30, 48, 80, 65),
    mechanics: ["Engine Building", "Card Drafting", "Dice Rolling"],
    categories: ["Animals", "Economic"],
    bggRating: 8.1,
    designer: "Elizabeth Hargrave",
    description: "Attract birds to your wildlife preserve and watch the engine sing.",
    expansions: [{ bggId: "290448", name: "European Expansion" }],
  },
  {
    bggId: "13",
    name: "Catan",
    yearPublished: 1995,
    players: { min: 3, max: 4, best: [4] },
    playtime: { min: 60, max: 120, avg: 90 },
    age: { publisher: 10, community: 10 },
    rubric: r(50, 55, 45, 70, 46, 70, 60),
    mechanics: ["Dice Rolling", "Trading", "Hexagon Grid", "Network Building"],
    categories: ["Economic", "Negotiation"],
    bggRating: 7.1,
    designer: "Klaus Teuber",
    description: "Settle the island, trade sheep for ore, and block the robber.",
  },
  {
    bggId: "9209",
    name: "Ticket to Ride",
    yearPublished: 2004,
    players: { min: 2, max: 5, best: [4] },
    playtime: { min: 30, max: 60, avg: 45 },
    age: { publisher: 8, community: 8 },
    rubric: r(35, 50, 40, 40, 36, 65, 45),
    mechanics: ["Set Collection", "Network Building", "Card Drafting"],
    categories: ["Trains", "Family"],
    bggRating: 7.4,
    designer: "Alan R. Moon",
    description: "Claim routes across a map before someone else snags your tickets.",
  },
  {
    bggId: "230802",
    name: "Azul",
    yearPublished: 2017,
    players: { min: 2, max: 4, best: [2, 3, 4] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 8, community: 8 },
    rubric: r(25, 60, 55, 25, 36, 75, 50),
    mechanics: ["Pattern Building", "Tile Placement", "Set Collection"],
    categories: ["Abstract Strategy"],
    bggRating: 7.8,
    designer: "Michael Kiesling",
    description: "Draft tiles, fill a mosaic, and leave the junk on someone else.",
  },
  {
    bggId: "30549",
    name: "Pandemic",
    yearPublished: 2008,
    players: { min: 2, max: 4, best: [4] },
    playtime: { min: 45, max: 60, avg: 50 },
    age: { publisher: 8, community: 10 },
    rubric: r(30, 65, 50, 72, 46, 45, 40),
    mechanics: ["Cooperative Game", "Set Collection", "Action Points"],
    categories: ["Medical", "Territory Building"],
    bggRating: 7.5,
    designer: "Matt Leacock",
    description: "Four diseases. One planet. You either save it together or you don't.",
  },
  {
    bggId: "822",
    name: "Carcassonne",
    yearPublished: 2000,
    players: { min: 2, max: 5, best: [2, 3] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 7, community: 7 },
    rubric: r(35, 50, 50, 40, 38, 70, 30),
    mechanics: ["Tile Placement", "Area Majority", "Map Addition"],
    categories: ["Medieval", "City Building"],
    bggRating: 7.4,
    designer: "Klaus-Jürgen Wrede",
    description: "Lay tiles, drop meeples, and steal a city at the last second.",
  },
  {
    bggId: "68448",
    name: "7 Wonders",
    yearPublished: 2010,
    players: { min: 3, max: 7, best: [4, 5, 6] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 10, community: 10 },
    rubric: r(25, 70, 55, 30, 48, 75, 70),
    mechanics: ["Card Drafting", "Simultaneous Action", "Set Collection"],
    categories: ["Ancient", "Civilization", "Economic"],
    bggRating: 7.7,
    designer: "Antoine Bauza",
    description: "Draft a civilization in three ages. Science, war, or wonders.",
  },
  {
    bggId: "173346",
    name: "7 Wonders Duel",
    yearPublished: 2015,
    players: { min: 2, max: 2, best: [2] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 10, community: 10 },
    rubric: r(15, 78, 70, 20, 50, 72, 68),
    mechanics: ["Card Drafting", "Tug of War", "Set Collection"],
    categories: ["Ancient", "Civilization"],
    bggRating: 8.1,
    designer: "Antoine Bauza",
    description: "The two-player 7 Wonders: three ways to win, zero wasted turns.",
  },
  {
    bggId: "36218",
    name: "Dominion",
    yearPublished: 2008,
    players: { min: 2, max: 4, best: [3] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 13, community: 10 },
    rubric: r(30, 70, 60, 20, 46, 90, 55),
    mechanics: ["Deck Building", "Hand Management", "Card Drafting"],
    categories: ["Card Game", "Medieval"],
    bggRating: 7.6,
    designer: "Donald X. Vaccarino",
    description: "The original deckbuilder. Ten kingdoms, infinite nights.",
  },
  {
    bggId: "167791",
    name: "Terraforming Mars",
    yearPublished: 2016,
    players: { min: 1, max: 5, best: [3, 4] },
    playtime: { min: 90, max: 180, avg: 120 },
    age: { publisher: 12, community: 12 },
    rubric: r(25, 90, 70, 25, 84, 85, 90),
    mechanics: ["Engine Building", "Hand Management", "Tile Placement", "Economic"],
    categories: ["Economic", "Science Fiction", "Territory Building"],
    bggRating: 8.4,
    designer: "Jacob Fryxelius",
    description: "Raise temperature, oxygen, and oceans — and your corporation.",
    expansions: [{ bggId: "219265", name: "Prelude" }],
  },
  {
    bggId: "169786",
    name: "Scythe",
    yearPublished: 2016,
    players: { min: 1, max: 5, best: [4] },
    playtime: { min: 90, max: 140, avg: 115 },
    age: { publisher: 14, community: 12 },
    rubric: r(15, 85, 70, 35, 80, 78, 85),
    mechanics: ["Area Majority", "Engine Building", "Worker Placement"],
    categories: ["Economic", "Fighting", "Science Fiction"],
    bggRating: 8.2,
    designer: "Jamey Stegmaier",
    description: "Mechs, farms, and a beautiful map. Efficiency is the real war.",
  },
  {
    bggId: "174430",
    name: "Gloomhaven",
    yearPublished: 2017,
    players: { min: 1, max: 4, best: [3] },
    playtime: { min: 60, max: 120, avg: 90 },
    age: { publisher: 14, community: 14 },
    rubric: r(20, 88, 80, 45, 92, 92, 70),
    mechanics: ["Campaign", "Hand Management", "Cooperative Game", "Grid Movement"],
    categories: ["Adventure", "Fantasy", "Fighting"],
    bggRating: 8.6,
    designer: "Isaac Childres",
    description: "A dungeon campaign in a box the size of a small child.",
  },
  {
    bggId: "162886",
    name: "Spirit Island",
    yearPublished: 2017,
    players: { min: 1, max: 4, best: [2] },
    playtime: { min: 90, max: 120, avg: 100 },
    age: { publisher: 13, community: 13 },
    rubric: r(15, 92, 80, 40, 88, 88, 75),
    mechanics: ["Cooperative Game", "Hand Management", "Variable Player Powers"],
    categories: ["Fantasy", "Fighting", "Territory Building"],
    bggRating: 8.4,
    designer: "R. Eric Reuss",
    description: "You are the island. The colonizers are the problem.",
  },
  {
    bggId: "224517",
    name: "Brass: Birmingham",
    yearPublished: 2018,
    players: { min: 2, max: 4, best: [3, 4] },
    playtime: { min: 60, max: 120, avg: 90 },
    age: { publisher: 14, community: 14 },
    rubric: r(10, 95, 80, 25, 86, 80, 95),
    mechanics: ["Network Building", "Hand Management", "Loans"],
    categories: ["Economic", "Industry / Manufacturing", "Trains"],
    bggRating: 8.6,
    designer: "Gavan Brown, Matt Tolman, Martin Wallace",
    description: "Canal then rail. Coal then beer. The heavyweight euro.",
  },
  {
    bggId: "233078",
    name: "Twilight Imperium (4th)",
    yearPublished: 2017,
    players: { min: 3, max: 6, best: [6] },
    playtime: { min: 240, max: 480, avg: 360 },
    age: { publisher: 14, community: 14 },
    rubric: r(20, 95, 75, 70, 96, 85, 80),
    mechanics: ["Negotiation", "Area Majority", "Voting", "Variable Player Powers"],
    categories: ["Civilization", "Negotiation", "Science Fiction", "Wargame"],
    bggRating: 8.6,
    designer: "Dane Beltrami, Corey Konieczka, Christian T. Petersen",
    description: "A whole Saturday. Galactic politics, war, and one last point.",
  },
  {
    bggId: "31260",
    name: "Agricola",
    yearPublished: 2007,
    players: { min: 1, max: 5, best: [3, 4] },
    playtime: { min: 30, max: 150, avg: 90 },
    age: { publisher: 12, community: 12 },
    rubric: r(15, 85, 70, 20, 82, 75, 92),
    mechanics: ["Worker Placement", "Hand Management", "Farming"],
    categories: ["Economic", "Farming"],
    bggRating: 7.9,
    designer: "Uwe Rosenberg",
    description: "Feed your family or take begging cards. Classic misery euro.",
  },
  {
    bggId: "148228",
    name: "Splendor",
    yearPublished: 2014,
    players: { min: 2, max: 4, best: [3] },
    playtime: { min: 30, max: 45, avg: 30 },
    age: { publisher: 10, community: 10 },
    rubric: r(20, 55, 50, 25, 36, 70, 60),
    mechanics: ["Set Collection", "Engine Building", "Card Drafting"],
    categories: ["Economic", "Renaissance"],
    bggRating: 7.4,
    designer: "Marc André",
    description: "Gems, cards, nobles. A clean engine you can teach in five minutes.",
  },
  {
    bggId: "70323",
    name: "King of Tokyo",
    yearPublished: 2011,
    players: { min: 2, max: 6, best: [4, 5] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 8, community: 8 },
    rubric: r(75, 30, 35, 80, 30, 70, 15),
    mechanics: ["Dice Rolling", "Player Elimination", "King of the Hill"],
    categories: ["Fighting", "Science Fiction"],
    bggRating: 7.1,
    designer: "Richard Garfield",
    description: "Monsters, dice, and the city of Tokyo. Push your luck, smash a rival.",
  },
  {
    bggId: "133473",
    name: "Sushi Go!",
    yearPublished: 2013,
    players: { min: 2, max: 5, best: [3, 4] },
    playtime: { min: 15, max: 20, avg: 15 },
    age: { publisher: 8, community: 6 },
    rubric: r(40, 30, 25, 45, 20, 65, 20),
    mechanics: ["Card Drafting", "Set Collection", "Simultaneous Action"],
    categories: ["Card Game"],
    bggRating: 7.0,
    designer: "Phil Walker-Harding",
    description: "Pass sushi. Keep the pudding. Fifteen minutes, zero fuss.",
  },
  {
    bggId: "277085",
    name: "Love Letter",
    yearPublished: 2012,
    players: { min: 2, max: 6, best: [4] },
    playtime: { min: 20, max: 30, avg: 20 },
    age: { publisher: 10, community: 8 },
    rubric: r(45, 35, 50, 60, 18, 70, 10),
    mechanics: ["Player Elimination", "Hand Management", "Deduction"],
    categories: ["Card Game", "Deduction", "Renaissance"],
    bggRating: 7.2,
    designer: "Seiji Kanai",
    description: "Sixteen cards, one princess, and a lot of bluffing.",
  },
  {
    bggId: "41114",
    name: "The Resistance",
    yearPublished: 2009,
    players: { min: 5, max: 10, best: [7, 8] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 13, community: 13 },
    rubric: r(20, 30, 55, 95, 24, 80, 5),
    mechanics: ["Hidden Roles", "Voting", "Traitor"],
    categories: ["Deduction", "Party Game", "Spies / Secret Agents"],
    bggRating: 7.2,
    designer: "Don Eskridge",
    description: "Spies in the mission. Trust no one. Talk anyway.",
  },
  {
    bggId: "188834",
    name: "Secret Hitler",
    yearPublished: 2016,
    players: { min: 5, max: 10, best: [7, 8] },
    playtime: { min: 30, max: 50, avg: 40 },
    age: { publisher: 13, community: 13 },
    rubric: r(25, 30, 55, 96, 28, 82, 5),
    mechanics: ["Hidden Roles", "Voting", "Traitor", "Negotiation"],
    categories: ["Deduction", "Party Game", "Political"],
    bggRating: 7.5,
    designer: "Max Temkin, Mike Boxleiter, Tommy Maranges",
    description: "Liberals, fascists, and one very quiet Hitler.",
  },
  {
    bggId: "172225",
    name: "Exploding Kittens",
    yearPublished: 2015,
    players: { min: 2, max: 5, best: [4] },
    playtime: { min: 15, max: 20, avg: 15 },
    age: { publisher: 7, community: 7 },
    rubric: r(80, 15, 20, 70, 16, 55, 5),
    mechanics: ["Player Elimination", "Take That", "Hand Management"],
    categories: ["Card Game", "Humor"],
    bggRating: 6.0,
    designer: "Matthew Inman, Elan Lee, Shane Small",
    description: "Draw a kitten, explode, or defuse. Chaotic and short.",
  },
  {
    bggId: "254640",
    name: "Just One",
    yearPublished: 2018,
    players: { min: 3, max: 7, best: [5, 6] },
    playtime: { min: 20, max: 30, avg: 20 },
    age: { publisher: 8, community: 8 },
    rubric: r(15, 15, 40, 90, 14, 80, 5),
    mechanics: ["Team-Based Game", "Communication Limits", "Word Game"],
    categories: ["Party Game", "Word Game"],
    bggRating: 7.6,
    designer: "Ted Alspach, Ludovic Roudy, Bruno Sautter",
    description: "Write a one-word clue. Duplicates vanish. Keep it unique.",
  },
  {
    bggId: "262543",
    name: "Wavelength",
    yearPublished: 2019,
    players: { min: 2, max: 12, best: [6, 7, 8] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 14, community: 12 },
    rubric: r(20, 20, 45, 93, 18, 85, 5),
    mechanics: ["Team-Based Game", "Communication Limits"],
    categories: ["Party Game", "Word Game"],
    bggRating: 7.4,
    designer: "Alex Hague, Justin Vickers, Wolfgang Warsch",
    description: "How spicy is too spicy? Point at a spectrum. Argue forever.",
  },
  {
    bggId: "244992",
    name: "The Mind",
    yearPublished: 2018,
    players: { min: 2, max: 4, best: [3, 4] },
    playtime: { min: 15, max: 20, avg: 18 },
    age: { publisher: 8, community: 8 },
    rubric: r(30, 10, 60, 80, 12, 70, 0),
    mechanics: ["Cooperative Game", "Communication Limits"],
    categories: ["Card Game", "Party Game"],
    bggRating: 6.9,
    designer: "Wolfgang Warsch",
    description: "Play cards in order. No talking. Feel the table breathe.",
  },
  {
    bggId: "92415",
    name: "Skull",
    yearPublished: 2011,
    players: { min: 3, max: 6, best: [5, 6] },
    playtime: { min: 15, max: 45, avg: 25 },
    age: { publisher: 10, community: 10 },
    rubric: r(25, 25, 70, 88, 16, 75, 5),
    mechanics: ["Betting", "Bluffing", "Player Elimination"],
    categories: ["Bluffing", "Party Game"],
    bggRating: 7.2,
    designer: "Hervé Marly",
    description: "Four discs, one skull, and a stare-down. Bluffing distilled.",
  },
  {
    bggId: "39856",
    name: "Dixit",
    yearPublished: 2008,
    players: { min: 3, max: 6, best: [5, 6] },
    playtime: { min: 30, max: 45, avg: 30 },
    age: { publisher: 8, community: 8 },
    rubric: r(20, 15, 35, 85, 20, 80, 5),
    mechanics: ["Voting", "Storytelling", "Hand Management"],
    categories: ["Party Game", "Humor"],
    bggRating: 7.2,
    designer: "Jean-Louis Roubira",
    description: "Dreamy art, a cryptic clue, and a vote for the right weirdness.",
  },
  {
    bggId: "163412",
    name: "Patchwork",
    yearPublished: 2014,
    players: { min: 2, max: 2, best: [2] },
    playtime: { min: 15, max: 30, avg: 25 },
    age: { publisher: 8, community: 6 },
    rubric: r(10, 70, 65, 15, 32, 72, 55),
    mechanics: ["Tile Placement", "Time Track", "Pattern Building"],
    categories: ["Abstract Strategy", "Puzzle"],
    bggRating: 7.6,
    designer: "Uwe Rosenberg",
    description: "Two-player Tetris quilts. Tight, kind, and endlessly replayable.",
  },
  {
    bggId: "295770",
    name: "Cascadia",
    yearPublished: 2021,
    players: { min: 1, max: 4, best: [2, 3] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 8, community: 8 },
    rubric: r(20, 55, 45, 20, 34, 78, 40),
    mechanics: ["Tile Placement", "Pattern Building", "Set Collection"],
    categories: ["Animals", "Environmental", "Puzzle"],
    bggRating: 7.9,
    designer: "Randy Flynn",
    description: "Habitats and wildlife. A quiet, pretty puzzle that always lands.",
  },
  {
    bggId: "199792",
    name: "Everdell",
    yearPublished: 2018,
    players: { min: 1, max: 4, best: [3] },
    playtime: { min: 40, max: 80, avg: 60 },
    age: { publisher: 13, community: 10 },
    rubric: r(20, 75, 55, 25, 58, 75, 75),
    mechanics: ["Worker Placement", "Engine Building", "Hand Management"],
    categories: ["Animals", "Card Game", "City Building", "Fantasy"],
    bggRating: 8.0,
    designer: "James A. Wilson",
    description: "Build a woodland city up a tree. Gorgeous and crunchy.",
  },
  {
    bggId: "237182",
    name: "Root",
    yearPublished: 2018,
    players: { min: 2, max: 4, best: [4] },
    playtime: { min: 60, max: 90, avg: 75 },
    age: { publisher: 10, community: 13 },
    rubric: r(20, 85, 80, 55, 78, 85, 60),
    mechanics: ["Area Majority", "Variable Player Powers", "Hand Management"],
    categories: ["Animals", "Fighting", "Wargame"],
    bggRating: 8.1,
    designer: "Cole Wehrle",
    description: "Asymmetric woodland war. Every faction is a different game.",
  },
  {
    bggId: "342942",
    name: "Ark Nova",
    yearPublished: 2021,
    players: { min: 1, max: 4, best: [2] },
    playtime: { min: 90, max: 150, avg: 120 },
    age: { publisher: 14, community: 13 },
    rubric: r(15, 90, 70, 20, 84, 82, 90),
    mechanics: ["Hand Management", "Tile Placement", "Engine Building"],
    categories: ["Animals", "Economic", "Environmental"],
    bggRating: 8.6,
    designer: "Mathias Wigge",
    description: "Build a modern zoo. Cards, conservation, and a long satisfying arc.",
  },
  {
    bggId: "316554",
    name: "Dune: Imperium",
    yearPublished: 2020,
    players: { min: 1, max: 4, best: [3, 4] },
    playtime: { min: 60, max: 120, avg: 90 },
    age: { publisher: 13, community: 13 },
    rubric: r(20, 88, 75, 40, 76, 85, 80),
    mechanics: ["Deck Building", "Worker Placement", "Area Majority"],
    categories: ["Movies / TV / Radio theme", "Science Fiction", "Political"],
    bggRating: 8.4,
    designer: "Paul Dennen",
    description: "Worker placement meets deckbuilding in the desert.",
  },
  {
    bggId: "312484",
    name: "Lost Ruins of Arnak",
    yearPublished: 2020,
    players: { min: 1, max: 4, best: [2, 3] },
    playtime: { min: 30, max: 120, avg: 75 },
    age: { publisher: 12, community: 12 },
    rubric: r(20, 80, 60, 25, 70, 78, 80),
    mechanics: ["Deck Building", "Worker Placement", "Set Collection"],
    categories: ["Adventure", "Exploration", "Fantasy"],
    bggRating: 8.1,
    designer: "Elwen, Mín",
    description: "Explore a lost island with workers and a growing deck.",
  },
  {
    bggId: "244521",
    name: "The Quacks of Quedlinburg",
    yearPublished: 2018,
    players: { min: 2, max: 4, best: [4] },
    playtime: { min: 45, max: 60, avg: 45 },
    age: { publisher: 10, community: 10 },
    rubric: r(70, 45, 35, 50, 40, 80, 40),
    mechanics: ["Push Your Luck", "Bag Building", "Catch the Leader"],
    categories: ["Fantasy"],
    bggRating: 7.8,
    designer: "Wolfgang Warsch",
    description: "Draw from your bag. Don't explode the potion. Maybe one more chip.",
  },
  {
    bggId: "284083",
    name: "The Crew: The Quest for Planet Nine",
    yearPublished: 2019,
    players: { min: 3, max: 5, best: [4] },
    playtime: { min: 20, max: 20, avg: 20 },
    age: { publisher: 10, community: 10 },
    rubric: r(25, 55, 70, 65, 30, 85, 10),
    mechanics: ["Cooperative Game", "Trick Taking", "Communication Limits"],
    categories: ["Card Game", "Science Fiction", "Space Exploration"],
    bggRating: 7.8,
    designer: "Thomas Sing",
    description: "Co-op trick-taking in space. Fifty missions, one silent table.",
  },
  {
    bggId: "385761",
    name: "Sky Team",
    yearPublished: 2023,
    players: { min: 2, max: 2, best: [2] },
    playtime: { min: 15, max: 20, avg: 15 },
    age: { publisher: 10, community: 12 },
    rubric: r(30, 50, 65, 70, 32, 80, 25),
    mechanics: ["Cooperative Game", "Dice Rolling", "Communication Limits"],
    categories: ["Aviation / Flight"],
    bggRating: 8.1,
    designer: "Luc Rémond",
    description: "Pilot and co-pilot land a plane. No talking in final approach.",
  },
  {
    bggId: "366013",
    name: "Heat: Pedal to the Metal",
    yearPublished: 2022,
    players: { min: 1, max: 6, best: [4, 5, 6] },
    playtime: { min: 30, max: 60, avg: 45 },
    age: { publisher: 10, community: 10 },
    rubric: r(35, 55, 60, 50, 42, 82, 40),
    mechanics: ["Hand Management", "Catch the Leader", "Simultaneous Action"],
    categories: ["Racing", "Sports"],
    bggRating: 8.0,
    designer: "Asger Harding Granerud, Daniel Skjold Pedersen",
    description: "Race cars, manage heat, and decide when to blow the engine.",
  },
  {
    bggId: "2655",
    name: "Hive",
    yearPublished: 2001,
    players: { min: 2, max: 2, best: [2] },
    playtime: { min: 20, max: 30, avg: 20 },
    age: { publisher: 9, community: 9 },
    rubric: r(5, 70, 85, 15, 40, 75, 10),
    mechanics: ["Grid Movement", "Pattern Building", "Tile Placement"],
    categories: ["Abstract Strategy", "Animals"],
    bggRating: 7.3,
    designer: "John Yianni",
    description: "No board. Surround the queen bee. Chess-like insects.",
  },
  {
    bggId: "171",
    name: "Chess",
    yearPublished: 1475,
    players: { min: 2, max: 2, best: [2] },
    playtime: { min: 10, max: 180, avg: 40 },
    age: { publisher: 6, community: 8 },
    rubric: r(0, 90, 95, 10, 70, 95, 20),
    mechanics: ["Grid Movement", "Pattern Recognition"],
    categories: ["Abstract Strategy"],
    bggRating: 7.2,
    designer: "Traditional",
    description: "The original skill ceiling. Still undefeated as a two-player war.",
  },
  {
    bggId: "194655",
    name: "Santorini",
    yearPublished: 2016,
    players: { min: 2, max: 2, best: [2] },
    playtime: { min: 20, max: 20, avg: 20 },
    age: { publisher: 8, community: 8 },
    rubric: r(5, 65, 80, 20, 30, 78, 15),
    mechanics: ["Grid Movement", "Variable Player Powers", "Tile Placement"],
    categories: ["Abstract Strategy", "Mythology"],
    bggRating: 7.4,
    designer: "Gordon Hamilton",
    description: "Build up, climb, and win. Gods make every match a new puzzle.",
  },
  {
    bggId: "160477",
    name: "Onitama",
    yearPublished: 2014,
    players: { min: 2, max: 2, best: [2] },
    playtime: { min: 15, max: 20, avg: 18 },
    age: { publisher: 8, community: 8 },
    rubric: r(10, 60, 80, 15, 28, 80, 10),
    mechanics: ["Grid Movement", "Hand Management"],
    categories: ["Abstract Strategy"],
    bggRating: 7.4,
    designer: "Shimpei Sato",
    description: "Five martial-arts cards. A pocket chess you can finish over coffee.",
  },
  {
    bggId: "131357",
    name: "Coup",
    yearPublished: 2012,
    players: { min: 2, max: 6, best: [5] },
    playtime: { min: 15, max: 20, avg: 15 },
    age: { publisher: 13, community: 10 },
    rubric: r(30, 25, 55, 88, 18, 75, 15),
    mechanics: ["Bluffing", "Player Elimination", "Deduction"],
    categories: ["Bluffing", "Card Game", "Deduction", "Party Game"],
    bggRating: 7.0,
    designer: "Rikki Tahta",
    description: "Claim a role. Get called. Lose a card. Fifteen minutes of lying.",
  },
  {
    bggId: "1406",
    name: "Monopoly",
    yearPublished: 1935,
    players: { min: 2, max: 8, best: [4] },
    playtime: { min: 60, max: 180, avg: 120 },
    age: { publisher: 8, community: 8 },
    rubric: r(70, 25, 20, 55, 30, 30, 40),
    mechanics: ["Dice Rolling", "Player Elimination", "Trading", "Roll / Spin and Move"],
    categories: ["Economic", "Negotiation"],
    bggRating: 4.4,
    designer: "Charles Darrow, Elizabeth Magie",
    description: "It's on the shelf. Finn will tell you when it's actually the pick.",
  },
  {
    bggId: "2223",
    name: "Uno",
    yearPublished: 1971,
    players: { min: 2, max: 10, best: [4, 5, 6] },
    playtime: { min: 15, max: 30, avg: 20 },
    age: { publisher: 6, community: 6 },
    rubric: r(75, 10, 15, 70, 12, 40, 5),
    mechanics: ["Hand Management", "Take That", "Shedding"],
    categories: ["Card Game", "Party Game"],
    bggRating: 5.5,
    designer: "Merle Robbins",
    description: "Draw two. Skip. Reverse. The family default for a reason.",
  },
  {
    bggId: "5048",
    name: "Candy Land",
    yearPublished: 1949,
    players: { min: 2, max: 4, best: [2, 3] },
    playtime: { min: 15, max: 30, avg: 20 },
    age: { publisher: 3, community: 3 },
    rubric: r(95, 0, 0, 30, 5, 10, 0),
    mechanics: ["Roll / Spin and Move"],
    categories: ["Children's Game", "Racing"],
    bggRating: 4.2,
    designer: "Eleanor Abbott",
    description: "Pure chance in a gumdrop forest. For the tiniest players only.",
  },
  {
    bggId: "1111",
    name: "Taboo",
    yearPublished: 1989,
    players: { min: 4, max: 10, best: [6, 8] },
    playtime: { min: 20, max: 30, avg: 25 },
    age: { publisher: 13, community: 12 },
    rubric: r(15, 10, 45, 92, 16, 70, 0),
    mechanics: ["Team-Based Game", "Real-Time", "Word Game"],
    categories: ["Party Game", "Word Game"],
    bggRating: 6.4,
    designer: "Brian Hersch",
    description: "Describe the word. Don't say the five you can't. Buzzers optional.",
  },
  {
    bggId: "21790",
    name: "Crokinole",
    yearPublished: 1876,
    players: { min: 2, max: 4, best: [2] },
    playtime: { min: 30, max: 30, avg: 30 },
    age: { publisher: 8, community: 6 },
    rubric: r(20, 20, 92, 50, 20, 80, 0),
    mechanics: ["Flicking"],
    categories: ["Action / Dexterity"],
    bggRating: 8.0,
    designer: "Traditional",
    description: "Flick discs. Kiss the 20. A skill toy dressed as a board game.",
  },
  {
    bggId: "50",
    name: "Lost Cities",
    yearPublished: 1999,
    players: { min: 2, max: 2, best: [2] },
    playtime: { min: 30, max: 30, avg: 30 },
    age: { publisher: 10, community: 10 },
    rubric: r(35, 55, 50, 20, 28, 70, 30),
    mechanics: ["Hand Management", "Push Your Luck", "Set Collection"],
    categories: ["Card Game", "Exploration"],
    bggRating: 7.1,
    designer: "Reiner Knizia",
    description: "Expeditions for two. Commit, or the handshake costs you.",
  },
  {
    bggId: "54043",
    name: "Jaipur",
    yearPublished: 2009,
    players: { min: 2, max: 2, best: [2] },
    playtime: { min: 30, max: 30, avg: 30 },
    age: { publisher: 12, community: 10 },
    rubric: r(25, 60, 55, 20, 32, 75, 55),
    mechanics: ["Set Collection", "Card Drafting", "Hand Management"],
    categories: ["Card Game", "Economic"],
    bggRating: 7.5,
    designer: "Sébastien Pauchon",
    description: "Camels, spices, and a two-player market that never sits still.",
  },
  {
    bggId: "2653",
    name: "Survive: Escape from Atlantis!",
    yearPublished: 1982,
    players: { min: 2, max: 4, best: [4] },
    playtime: { min: 45, max: 60, avg: 50 },
    age: { publisher: 8, community: 10 },
    rubric: r(55, 40, 35, 75, 34, 70, 20),
    mechanics: ["Pick-up and Deliver", "Player Elimination", "Dice Rolling"],
    categories: ["Adventure", "Nautical"],
    bggRating: 7.3,
    designer: "Julian Courtland-Smith",
    description: "Get your people off the sinking island. Sea monsters included.",
  },
  {
    bggId: "2651",
    name: "Power Grid",
    yearPublished: 2004,
    players: { min: 2, max: 6, best: [4, 5] },
    playtime: { min: 120, max: 120, avg: 120 },
    age: { publisher: 12, community: 12 },
    rubric: r(10, 88, 70, 30, 78, 70, 92),
    mechanics: ["Auction", "Network Building", "Economic"],
    categories: ["Economic", "Industry / Manufacturing"],
    bggRating: 7.8,
    designer: "Friedemann Friese",
    description: "Buy plants, buy fuel, light cities. The market is the opponent.",
  },
  {
    bggId: "3076",
    name: "Puerto Rico",
    yearPublished: 2002,
    players: { min: 3, max: 5, best: [4] },
    playtime: { min: 90, max: 150, avg: 120 },
    age: { publisher: 12, community: 12 },
    rubric: r(10, 90, 75, 20, 80, 70, 90),
    mechanics: ["Role Selection", "Economic"],
    categories: ["Economic", "Farming"],
    bggRating: 7.9,
    designer: "Andreas Seyfarth",
    description: "Roles, plantations, and shipping. A landmark engine.",
  },
  {
    bggId: "199561",
    name: "Sagrada",
    yearPublished: 2017,
    players: { min: 1, max: 4, best: [2] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 10, community: 10 },
    rubric: r(40, 50, 50, 20, 34, 75, 35),
    mechanics: ["Dice Rolling", "Pattern Building", "Window Building"],
    categories: ["Dice", "Puzzle"],
    bggRating: 7.5,
    designer: "Adrian Adamescu, Stefan Alexander",
    description: "Stained-glass windows from dice. Pretty, tight, and teachable.",
  },
  {
    bggId: "263918",
    name: "Cartographers",
    yearPublished: 2019,
    players: { min: 1, max: 100, best: [4] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 10, community: 10 },
    rubric: r(30, 50, 45, 25, 32, 80, 25),
    mechanics: ["Paper-and-Pencil", "Tile Placement", "Bingo"],
    categories: ["Fantasy", "Territory Building"],
    bggRating: 7.7,
    designer: "Jordy Adan",
    description: "Draw a map from flip cards. Scales to the whole table.",
  },
  {
    bggId: "170216",
    name: "Blood Rage",
    yearPublished: 2015,
    players: { min: 2, max: 4, best: [4] },
    playtime: { min: 60, max: 90, avg: 75 },
    age: { publisher: 14, community: 14 },
    rubric: r(20, 80, 65, 50, 70, 75, 55),
    mechanics: ["Area Majority", "Card Drafting", "Fighting"],
    categories: ["Fantasy", "Fighting", "Mythology", "Norse"],
    bggRating: 7.9,
    designer: "Eric M. Lang",
    description: "Vikings, Ragnarok, and glorious death that scores.",
  },
  {
    bggId: "205597",
    name: "Rising Sun",
    yearPublished: 2018,
    players: { min: 3, max: 5, best: [4, 5] },
    playtime: { min: 90, max: 120, avg: 100 },
    age: { publisher: 14, community: 14 },
    rubric: r(15, 82, 65, 60, 76, 72, 55),
    mechanics: ["Area Majority", "Negotiation", "Auction"],
    categories: ["Fantasy", "Mythology", "Negotiation"],
    bggRating: 7.8,
    designer: "Eric M. Lang",
    description: "Alliances, betrayals, and monsters in feudal Japan.",
  },
  {
    bggId: "242302",
    name: "That's Pretty Clever!",
    yearPublished: 2018,
    players: { min: 1, max: 4, best: [2] },
    playtime: { min: 30, max: 30, avg: 30 },
    age: { publisher: 8, community: 8 },
    rubric: r(45, 50, 50, 20, 30, 78, 35),
    mechanics: ["Dice Rolling", "Paper-and-Pencil"],
    categories: ["Dice", "Number"],
    bggRating: 7.6,
    designer: "Wolfgang Warsch",
    description: "Pick a die, fill a sheet, combo off yourself. Solo-friendly.",
  },
  {
    bggId: "287954",
    name: "Azul: Summer Pavilion",
    yearPublished: 2019,
    players: { min: 2, max: 4, best: [2, 3] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 8, community: 8 },
    rubric: r(25, 62, 55, 22, 38, 76, 52),
    mechanics: ["Pattern Building", "Tile Placement", "Set Collection"],
    categories: ["Abstract Strategy"],
    bggRating: 7.8,
    designer: "Michael Kiesling",
    description: "Azul with wilds and a star. Same click, new puzzle.",
  },
  {
    bggId: "286096",
    name: "Tainted Grail",
    yearPublished: 2019,
    players: { min: 1, max: 4, best: [1, 2] },
    playtime: { min: 60, max: 120, avg: 90 },
    age: { publisher: 14, community: 14 },
    rubric: r(25, 70, 55, 40, 80, 70, 45),
    mechanics: ["Campaign", "Storytelling", "Cooperative Game"],
    categories: ["Adventure", "Fantasy"],
    bggRating: 8.0,
    designer: "Krzysztof Piskorski, Marcin Świerkot",
    description: "A grim Arthurian campaign. Heavy on story, light on mercy.",
  },
  {
    bggId: "291572",
    name: "Wonderland's War",
    yearPublished: 2022,
    players: { min: 2, max: 5, best: [3, 4] },
    playtime: { min: 45, max: 125, avg: 90 },
    age: { publisher: 13, community: 13 },
    rubric: r(30, 75, 60, 40, 72, 78, 55),
    mechanics: ["Area Majority", "Bag Building", "Variable Player Powers"],
    categories: ["Fantasy", "Fighting"],
    bggRating: 8.0,
    designer: "Tim Eisner, Ben Eisner, Ian Moss",
    description: "Bag-building war in Wonderland. Weird in the best way.",
  },
  {
    bggId: "31260-revised",
    name: "Agricola: All Creatures Big and Small",
    yearPublished: 2012,
    players: { min: 2, max: 2, best: [2] },
    playtime: { min: 30, max: 30, avg: 30 },
    age: { publisher: 9, community: 9 },
    rubric: r(10, 70, 55, 15, 40, 65, 80),
    mechanics: ["Worker Placement", "Tile Placement"],
    categories: ["Animals", "Farming"],
    bggRating: 7.3,
    designer: "Uwe Rosenberg",
    description: "A 30-minute farm for two. No begging cards, still tight.",
  },
  {
    bggId: "266810",
    name: "Paladins of the West Kingdom",
    yearPublished: 2019,
    players: { min: 1, max: 4, best: [2] },
    playtime: { min: 90, max: 120, avg: 100 },
    age: { publisher: 12, community: 12 },
    rubric: r(10, 88, 70, 20, 80, 75, 90),
    mechanics: ["Worker Placement", "Hand Management"],
    categories: ["Medieval", "Religious"],
    bggRating: 8.1,
    designer: "Shem Phillips, S J Macdonald",
    description: "Workers with jobs. A dense, satisfying West Kingdom euro.",
  },
  {
    bggId: "28143",
    name: "Race for the Galaxy",
    yearPublished: 2007,
    players: { min: 2, max: 4, best: [2] },
    playtime: { min: 30, max: 60, avg: 45 },
    age: { publisher: 12, community: 12 },
    rubric: r(25, 80, 75, 15, 72, 85, 70),
    mechanics: ["Hand Management", "Simultaneous Action", "Engine Building"],
    categories: ["Card Game", "Civilization", "Economic", "Science Fiction"],
    bggRating: 7.8,
    designer: "Thomas Lehmann",
    description: "Tableau building at speed. Icons first, then it clicks forever.",
  },
  {
    bggId: "41",
    name: "Can't Stop",
    yearPublished: 1980,
    players: { min: 2, max: 4, best: [3, 4] },
    playtime: { min: 30, max: 30, avg: 30 },
    age: { publisher: 7, community: 8 },
    rubric: r(70, 20, 40, 60, 18, 75, 5),
    mechanics: ["Dice Rolling", "Push Your Luck"],
    categories: ["Dice"],
    bggRating: 6.9,
    designer: "Sid Sackson",
    description: "Climb three columns. Stop — or don't. The perfect luck game.",
  },
  {
    bggId: "811",
    name: "Rummikub",
    yearPublished: 1977,
    players: { min: 2, max: 4, best: [4] },
    playtime: { min: 30, max: 60, avg: 40 },
    age: { publisher: 8, community: 8 },
    rubric: r(40, 35, 50, 40, 24, 60, 10),
    mechanics: ["Set Collection", "Tile Placement"],
    categories: ["Abstract Strategy", "Number"],
    bggRating: 6.5,
    designer: "Ephraim Hertzano",
    description: "Rummy with tiles. Manipulation puzzles for the family table.",
  },
  {
    bggId: "2453",
    name: "Blokus",
    yearPublished: 2000,
    players: { min: 2, max: 4, best: [4] },
    playtime: { min: 20, max: 30, avg: 25 },
    age: { publisher: 5, community: 7 },
    rubric: r(5, 50, 70, 30, 22, 70, 10),
    mechanics: ["Tile Placement", "Area Enclosure"],
    categories: ["Abstract Strategy", "Territory Building"],
    bggRating: 6.8,
    designer: "Bernard Tavitian",
    description: "Corner-to-corner polyominoes. Easy to start, nasty to master.",
  },
  {
    bggId: "25669",
    name: "Qwirkle",
    yearPublished: 2006,
    players: { min: 2, max: 4, best: [3] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 6, community: 6 },
    rubric: r(25, 35, 45, 30, 18, 65, 10),
    mechanics: ["Pattern Building", "Tile Placement", "Set Collection"],
    categories: ["Abstract Strategy"],
    bggRating: 6.7,
    designer: "Susan McKinley Ross",
    description: "Colors and shapes. A Scrabble-cousin that kids can actually play.",
  },
  {
    bggId: "1294",
    name: "Clue",
    yearPublished: 1949,
    players: { min: 2, max: 6, best: [4, 5] },
    playtime: { min: 30, max: 60, avg: 45 },
    age: { publisher: 8, community: 8 },
    rubric: r(40, 40, 50, 55, 28, 40, 10),
    mechanics: ["Deduction", "Roll / Spin and Move", "Paper-and-Pencil"],
    categories: ["Deduction", "Murder / Mystery"],
    bggRating: 5.7,
    designer: "Anthony E. Pratt",
    description: "Miss Scarlet, the lounge, the candlestick. Deduction with dice.",
  },
  {
    bggId: "1293",
    name: "Boggle",
    yearPublished: 1972,
    players: { min: 1, max: 8, best: [4] },
    playtime: { min: 10, max: 20, avg: 10 },
    age: { publisher: 8, community: 8 },
    rubric: r(30, 10, 70, 50, 14, 70, 0),
    mechanics: ["Real-Time", "Spelling"],
    categories: ["Word Game", "Party Game", "Real-time"],
    bggRating: 6.2,
    designer: "Allan Turoff",
    description: "Shake the grid. Three minutes. Find the words nobody else saw.",
  },
  {
    bggId: "320",
    name: "Scrabble",
    yearPublished: 1948,
    players: { min: 2, max: 4, best: [2] },
    playtime: { min: 45, max: 90, avg: 60 },
    age: { publisher: 10, community: 10 },
    rubric: r(30, 50, 80, 25, 40, 75, 20),
    mechanics: ["Tile Placement", "Hand Management", "Spelling"],
    categories: ["Word Game"],
    bggRating: 6.3,
    designer: "Alfred Mosher Butts",
    description: "The word game. Skill, vocabulary, and a well-placed Q.",
  },
  {
    bggId: "3931",
    name: "Connect Four",
    yearPublished: 1974,
    players: { min: 2, max: 2, best: [2] },
    playtime: { min: 10, max: 10, avg: 10 },
    age: { publisher: 6, community: 6 },
    rubric: r(5, 40, 55, 20, 12, 50, 0),
    mechanics: ["Pattern Building"],
    categories: ["Abstract Strategy", "Children's Game"],
    bggRating: 4.9,
    designer: "Howard Wexler, Ned Strongin",
    description: "Four in a row. A five-minute duel with a surprising amount of trap-setting.",
  },
  {
    bggId: "2452",
    name: "Jenga",
    yearPublished: 1983,
    players: { min: 1, max: 8, best: [4] },
    playtime: { min: 10, max: 20, avg: 15 },
    age: { publisher: 6, community: 6 },
    rubric: r(40, 10, 70, 75, 8, 55, 0),
    mechanics: ["Player Elimination"],
    categories: ["Action / Dexterity", "Party Game"],
    bggRating: 5.6,
    designer: "Leslie Scott",
    description: "Pull a block. Stack it. Don't be the one who topples the tower.",
  },
  {
    bggId: "1410",
    name: "Pictionary",
    yearPublished: 1985,
    players: { min: 3, max: 16, best: [6, 8] },
    playtime: { min: 30, max: 60, avg: 45 },
    age: { publisher: 12, community: 10 },
    rubric: r(20, 5, 40, 92, 12, 65, 0),
    mechanics: ["Team-Based Game", "Drawing", "Real-Time"],
    categories: ["Party Game"],
    bggRating: 6.0,
    designer: "Rob Angel",
    description: "Draw it. Don't talk. Watch the table yell the wrong animal.",
  },
  {
    bggId: "4112",
    name: "Sequence",
    yearPublished: 1982,
    players: { min: 2, max: 12, best: [4, 6] },
    playtime: { min: 10, max: 45, avg: 25 },
    age: { publisher: 7, community: 7 },
    rubric: r(45, 30, 30, 50, 16, 50, 5),
    mechanics: ["Hand Management", "Pattern Building", "Partnerships"],
    categories: ["Abstract Strategy", "Card Game"],
    bggRating: 6.3,
    designer: "Doug Reuter",
    description: "Cards plus a board. Make five in a row with a partner.",
  },
  {
    bggId: "2083",
    name: "Yahtzee",
    yearPublished: 1956,
    players: { min: 2, max: 10, best: [3, 4] },
    playtime: { min: 20, max: 40, avg: 30 },
    age: { publisher: 6, community: 6 },
    rubric: r(80, 20, 25, 40, 14, 55, 5),
    mechanics: ["Dice Rolling", "Paper-and-Pencil", "Push Your Luck"],
    categories: ["Dice"],
    bggRating: 5.5,
    designer: "Edwin S. Lowe, ‎Toy Company",
    description: "Five dice, thirteen boxes, and the eternal Yahtzee hope.",
  },
  {
    bggId: "8110",
    name: "Left Right Center",
    yearPublished: 1992,
    players: { min: 3, max: 15, best: [6, 8] },
    playtime: { min: 10, max: 20, avg: 15 },
    age: { publisher: 5, community: 5 },
    rubric: r(98, 0, 0, 70, 6, 20, 0),
    mechanics: ["Dice Rolling", "Player Elimination"],
    categories: ["Dice", "Party Game"],
    bggRating: 3.8,
    designer: "George & Betty Spinello",
    description: "Roll L, R, or C. Pass chips. Pure chance, pure table noise.",
  },
  {
    bggId: "4118",
    name: "The Game of Life",
    yearPublished: 1960,
    players: { min: 2, max: 6, best: [4] },
    playtime: { min: 45, max: 60, avg: 50 },
    age: { publisher: 8, community: 6 },
    rubric: r(85, 10, 5, 45, 16, 25, 10),
    mechanics: ["Roll / Spin and Move"],
    categories: ["Children's Game", "Economic"],
    bggRating: 4.3,
    designer: "Reuben Klamer, Bill Markham",
    description: "Spin, career, kids, retirement. A story more than a game.",
  },
  {
    bggId: "157969",
    name: "Sheriff of Nottingham",
    yearPublished: 2014,
    players: { min: 3, max: 5, best: [5] },
    playtime: { min: 60, max: 60, avg: 55 },
    age: { publisher: 13, community: 10 },
    rubric: r(30, 30, 55, 88, 32, 75, 20),
    mechanics: ["Bluffing", "Negotiation", "Card Drafting"],
    categories: ["Bluffing", "Medieval", "Negotiation"],
    bggRating: 7.1,
    designer: "Sergio Halaban, André Zatz",
    description: "Smuggle contraband. Bribe the sheriff. Laugh when it backfires.",
  },
  {
    bggId: "181304",
    name: "Mysterium",
    yearPublished: 2015,
    players: { min: 2, max: 7, best: [5, 6] },
    playtime: { min: 42, max: 42, avg: 42 },
    age: { publisher: 10, community: 10 },
    rubric: r(20, 20, 40, 85, 28, 75, 5),
    mechanics: ["Communication Limits", "Deduction", "Team-Based Game"],
    categories: ["Deduction", "Murder / Mystery", "Party Game"],
    bggRating: 7.3,
    designer: "Oleksandr Nevskiy, Oleg Sidorenko",
    description: "A ghost hands out visions. Psychics guess the murder. Dreamy.",
  },
  {
    bggId: "156129",
    name: "Deception: Murder in Hong Kong",
    yearPublished: 2014,
    players: { min: 4, max: 12, best: [6, 7, 8] },
    playtime: { min: 20, max: 30, avg: 25 },
    age: { publisher: 14, community: 14 },
    rubric: r(15, 25, 55, 94, 28, 80, 5),
    mechanics: ["Hidden Roles", "Deduction", "Traitor"],
    categories: ["Bluffing", "Deduction", "Murder / Mystery", "Party Game"],
    bggRating: 7.5,
    designer: "Tobey Ho",
    description: "One murderer, one forensic scientist, a table of suspects.",
  },
  {
    bggId: "198773",
    name: "Codenames: Pictures",
    yearPublished: 2016,
    players: { min: 4, max: 8, best: [6] },
    playtime: { min: 15, max: 30, avg: 20 },
    age: { publisher: 10, community: 10 },
    rubric: r(35, 20, 45, 90, 18, 85, 5),
    mechanics: ["Team-Based Game", "Communication Limits", "Deduction"],
    categories: ["Party Game", "Spies / Secret Agents"],
    bggRating: 7.4,
    designer: "Vlaada Chvátil",
    description: "Codenames with art instead of words. Looser, louder, still deadly.",
  },
  {
    bggId: "217372",
    name: "The Quest for El Dorado",
    yearPublished: 2017,
    players: { min: 2, max: 4, best: [4] },
    playtime: { min: 30, max: 60, avg: 45 },
    age: { publisher: 10, community: 10 },
    rubric: r(25, 55, 50, 40, 36, 78, 45),
    mechanics: ["Deck Building", "Grid Movement", "Modular Board"],
    categories: ["Adventure", "Racing"],
    bggRating: 7.6,
    designer: "Reiner Knizia",
    description: "A deckbuilding race through the jungle. Knizia at his friendliest.",
  },
  {
    bggId: "266083",
    name: "The Isle of Cats",
    yearPublished: 2019,
    players: { min: 1, max: 4, best: [2, 3] },
    playtime: { min: 60, max: 90, avg: 70 },
    age: { publisher: 8, community: 8 },
    rubric: r(20, 60, 50, 25, 46, 75, 50),
    mechanics: ["Polyominoes", "Card Drafting", "Tile Placement"],
    categories: ["Animals", "Puzzle"],
    bggRating: 7.6,
    designer: "Frank West",
    description: "Rescue cats, pack the boat. Polyomino comfort food.",
  },
  {
    bggId: "281555",
    name: "The King Is Dead: Second Edition",
    yearPublished: 2020,
    players: { min: 2, max: 4, best: [3] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 12, community: 12 },
    rubric: r(10, 80, 75, 40, 48, 80, 30),
    mechanics: ["Area Majority", "Hand Management"],
    categories: ["Medieval", "Political", "Territory Building"],
    bggRating: 7.6,
    designer: "Peer Sylvester",
    description: "Short, vicious majority. Britain, factions, and a last loyalist.",
  },
  {
    bggId: "169255",
    name: "The Grizzled",
    yearPublished: 2015,
    players: { min: 2, max: 5, best: [4] },
    playtime: { min: 30, max: 30, avg: 30 },
    age: { publisher: 14, community: 12 },
    rubric: r(30, 40, 40, 70, 32, 65, 10),
    mechanics: ["Cooperative Game", "Communication Limits", "Hand Management"],
    categories: ["World War I"],
    bggRating: 7.1,
    designer: "Fabien Riffaud, Juan Rodriguez",
    description: "Survive the trenches together. Quiet, heavy, 30 minutes.",
  },
  {
    bggId: "233078-short",
    name: "Dune (2019)",
    yearPublished: 2019,
    players: { min: 3, max: 6, best: [6] },
    playtime: { min: 120, max: 180, avg: 150 },
    age: { publisher: 14, community: 14 },
    rubric: r(15, 85, 70, 80, 78, 75, 50),
    mechanics: ["Area Majority", "Negotiation", "Auction", "Traitor"],
    categories: ["Bluffing", "Negotiation", "Political", "Science Fiction"],
    bggRating: 8.0,
    designer: "Bill Eberle, Jack Kittredge, Peter Olotka, Greg Olotka, Jack Reda",
    description: "Alliances, treachery, and spice. Diplomacy with sand.",
  },
  {
    bggId: "164153",
    name: "Star Realms",
    yearPublished: 2014,
    players: { min: 2, max: 2, best: [2] },
    playtime: { min: 20, max: 20, avg: 20 },
    age: { publisher: 12, community: 10 },
    rubric: r(30, 55, 55, 15, 32, 82, 40),
    mechanics: ["Deck Building", "Take That"],
    categories: ["Card Game", "Fighting", "Science Fiction"],
    bggRating: 7.6,
    designer: "Darwin Kastle, Rob Dougherty",
    description: "Pocket deckbuilder. Combat, bases, and a twenty-minute duel.",
  },
  {
    bggId: "265402",
    name: "Final Girl",
    yearPublished: 2021,
    players: { min: 1, max: 1, best: [1] },
    playtime: { min: 20, max: 60, avg: 45 },
    age: { publisher: 14, community: 14 },
    rubric: r(35, 60, 50, 5, 50, 80, 30),
    mechanics: ["Solo", "Hand Management", "Variable Player Powers"],
    categories: ["Horror", "Movies / TV / Radio theme"],
    bggRating: 8.0,
    designer: "A. J. Porfirio",
    description: "You are the last one left. A solo horror film in a box.",
  },
  {
    bggId: "414317",
    name: "Harmonies",
    yearPublished: 2024,
    players: { min: 1, max: 4, best: [2, 3] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 10, community: 10 },
    rubric: r(20, 55, 45, 20, 36, 78, 40),
    mechanics: ["Pattern Building", "Tile Placement", "Set Collection"],
    categories: ["Animals", "Environmental", "Puzzle"],
    bggRating: 7.8,
    designer: "Johan Benvenuto",
    description: "Landscapes, animals, and a gentle spatial puzzle.",
  },
  {
    bggId: "366161",
    name: "Forest Shuffle",
    yearPublished: 2023,
    players: { min: 2, max: 4, best: [2] },
    playtime: { min: 40, max: 60, avg: 45 },
    age: { publisher: 10, community: 10 },
    rubric: r(25, 65, 50, 20, 44, 80, 55),
    mechanics: ["Hand Management", "Set Collection", "Tableau Building"],
    categories: ["Animals", "Card Game", "Environmental"],
    bggRating: 7.6,
    designer: "Kosch",
    description: "Fill a forest with cards that combo off their neighbors.",
  },
  {
    bggId: "318184",
    name: "Wonderland's War",
    yearPublished: 2022,
    players: { min: 2, max: 5, best: [4] },
    playtime: { min: 45, max: 125, avg: 90 },
    age: { publisher: 14, community: 13 },
    rubric: r(28, 76, 62, 42, 74, 77, 58),
    mechanics: ["Area Majority", "Bag Building"],
    categories: ["Fantasy", "Fighting"],
    bggRating: 8.0,
    designer: "Tim Eisner",
    description: "Duplicate skipped — using Faraway instead.",
  },
  {
    bggId: "385565",
    name: "Faraway",
    yearPublished: 2023,
    players: { min: 2, max: 6, best: [3, 4] },
    playtime: { min: 15, max: 30, avg: 20 },
    age: { publisher: 10, community: 10 },
    rubric: r(25, 55, 40, 20, 30, 80, 35),
    mechanics: ["Card Drafting", "Set Collection", "End Game Bonuses"],
    categories: ["Card Game", "Fantasy"],
    bggRating: 7.5,
    designer: "Johannes Krenner, Johann Gardeux",
    description: "Draft a journey, score it backwards. Tiny box, clever hook.",
  },
  {
    bggId: "359871",
    name: "The White Castle",
    yearPublished: 2023,
    players: { min: 1, max: 4, best: [2, 3] },
    playtime: { min: 40, max: 80, avg: 60 },
    age: { publisher: 12, community: 12 },
    rubric: r(20, 80, 60, 20, 62, 75, 85),
    mechanics: ["Dice Placement", "Worker Placement", "Engine Building"],
    categories: ["Dice", "Economic", "Medieval"],
    bggRating: 8.0,
    designer: "Israel Cendrero, Sheila Santos",
    description: "A tight Himeji euro. Dice as workers, zero wasted motion.",
  },
  {
    bggId: "3955",
    name: "Pandemic: Hot Zone — North America",
    yearPublished: 2020,
    players: { min: 2, max: 4, best: [3] },
    playtime: { min: 30, max: 30, avg: 30 },
    age: { publisher: 8, community: 8 },
    rubric: r(30, 55, 45, 70, 32, 55, 30),
    mechanics: ["Cooperative Game", "Set Collection", "Action Points"],
    categories: ["Medical"],
    bggRating: 7.2,
    designer: "Matt Leacock, Thomas Lehmann",
    description: "Pandemic in 30 minutes. Same panic, smaller map.",
  },
  {
    bggId: "266810-architects",
    name: "Architects of the West Kingdom",
    yearPublished: 2018,
    players: { min: 1, max: 5, best: [3, 4] },
    playtime: { min: 60, max: 80, avg: 70 },
    age: { publisher: 12, community: 12 },
    rubric: r(15, 80, 60, 25, 68, 75, 85),
    mechanics: ["Worker Placement", "Engine Building"],
    categories: ["City Building", "Medieval"],
    bggRating: 7.8,
    designer: "Shem Phillips, S J Macdonald",
    description: "Build the cathedral, capture workers, and manage virtue.",
  },
  {
    bggId: "266192-asia",
    name: "Apiary",
    yearPublished: 2023,
    players: { min: 1, max: 5, best: [3] },
    playtime: { min: 60, max: 90, avg: 75 },
    age: { publisher: 13, community: 12 },
    rubric: r(15, 78, 55, 22, 64, 76, 80),
    mechanics: ["Worker Placement", "Engine Building"],
    categories: ["Animals", "Science Fiction"],
    bggRating: 7.7,
    designer: "Connie Vogelmann",
    description: "Space bees. Workers age, farms grow, a gentle euro hum.",
  },
  {
    bggId: "199792-bellfaire",
    name: "The Search for Planet X",
    yearPublished: 2020,
    players: { min: 1, max: 4, best: [2, 3] },
    playtime: { min: 60, max: 75, avg: 60 },
    age: { publisher: 13, community: 13 },
    rubric: r(10, 70, 80, 25, 52, 78, 30),
    mechanics: ["Deduction", "Paper-and-Pencil"],
    categories: ["Deduction", "Science Fiction", "Space Exploration"],
    bggRating: 7.7,
    designer: "Matthew O'Malley, Ben Rosset",
    description: "A logic puzzle in the sky. Survey, deduce, find Planet X.",
  },
  {
    bggId: "295947",
    name: "So Clover!",
    yearPublished: 2021,
    players: { min: 3, max: 6, best: [4, 5] },
    playtime: { min: 20, max: 30, avg: 25 },
    age: { publisher: 10, community: 10 },
    rubric: r(10, 15, 40, 90, 16, 82, 0),
    mechanics: ["Team-Based Game", "Word Game", "Communication Limits"],
    categories: ["Party Game", "Word Game"],
    bggRating: 7.4,
    designer: "François Gandon",
    description: "Four keywords, one clover of clues. Cooperative wordplay.",
  },
  {
    bggId: "244049",
    name: "The Mind Extreme",
    yearPublished: 2021,
    players: { min: 2, max: 4, best: [3] },
    playtime: { min: 20, max: 20, avg: 20 },
    age: { publisher: 8, community: 8 },
    rubric: r(30, 15, 65, 82, 16, 72, 0),
    mechanics: ["Cooperative Game", "Communication Limits"],
    categories: ["Card Game", "Party Game"],
    bggRating: 7.0,
    designer: "Wolfgang Warsch",
    description: "The Mind, plus a second row. Even less talking.",
  },
  {
    bggId: "291453",
    name: "Fun Facts",
    yearPublished: 2022,
    players: { min: 4, max: 8, best: [6] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 8, community: 10 },
    rubric: r(10, 5, 20, 92, 12, 75, 0),
    mechanics: ["Voting", "Party"],
    categories: ["Party Game"],
    bggRating: 7.2,
    designer: "Kasper Lapp",
    description: "Rank yourselves on a spectrum. Learn who actually likes cilantro.",
  },
  {
    bggId: "13-junior",
    name: "Outfoxed!",
    yearPublished: 2016,
    players: { min: 2, max: 4, best: [3, 4] },
    playtime: { min: 20, max: 20, avg: 20 },
    age: { publisher: 5, community: 5 },
    rubric: r(35, 25, 30, 70, 16, 55, 10),
    mechanics: ["Cooperative Game", "Deduction", "Dice Rolling"],
    categories: ["Children's Game", "Deduction"],
    bggRating: 6.8,
    designer: "Kane Klenko",
    description: "A co-op whodunit for kids. Catch the fox before he escapes.",
  },
  {
    bggId: "65244",
    name: "Forbidden Island",
    yearPublished: 2010,
    players: { min: 2, max: 4, best: [4] },
    playtime: { min: 30, max: 30, avg: 30 },
    age: { publisher: 10, community: 8 },
    rubric: r(35, 45, 35, 70, 28, 50, 20),
    mechanics: ["Cooperative Game", "Set Collection", "Grid Movement"],
    categories: ["Adventure", "Fantasy"],
    bggRating: 6.8,
    designer: "Matt Leacock",
    description: "Grab the treasures, get off the island, don't drown.",
  },
  {
    bggId: "65200",
    name: "Forbidden Desert",
    yearPublished: 2013,
    players: { min: 2, max: 5, best: [4] },
    playtime: { min: 45, max: 45, avg: 45 },
    age: { publisher: 10, community: 10 },
    rubric: r(35, 55, 40, 70, 36, 55, 25),
    mechanics: ["Cooperative Game", "Grid Movement", "Set Collection"],
    categories: ["Adventure", "Arabian"],
    bggRating: 7.1,
    designer: "Matt Leacock",
    description: "A flying machine under the sand. Thirst is the real enemy.",
  },
  {
    bggId: "209418",
    name: "Rhino Hero",
    yearPublished: 2011,
    players: { min: 2, max: 5, best: [3, 4] },
    playtime: { min: 5, max: 15, avg: 10 },
    age: { publisher: 5, community: 5 },
    rubric: r(30, 10, 60, 75, 8, 65, 0),
    mechanics: ["Stacking"],
    categories: ["Action / Dexterity", "Animals", "Children's Game"],
    bggRating: 6.9,
    designer: "Scott Frisco, Steven Strumpf",
    description: "Build a cardboard skyscraper. Place the rhino. Don't sneeze.",
  },
  {
    bggId: "177678",
    name: "Ice Cool",
    yearPublished: 2016,
    players: { min: 2, max: 4, best: [4] },
    playtime: { min: 20, max: 30, avg: 25 },
    age: { publisher: 6, community: 6 },
    rubric: r(25, 15, 80, 70, 12, 75, 0),
    mechanics: ["Flicking"],
    categories: ["Action / Dexterity", "Animals", "Children's Game"],
    bggRating: 7.0,
    designer: "Brian Gomez",
    description: "Flick penguins through a school. Dexterity joy in a tin.",
  },
  {
    bggId: "21790-pitch",
    name: "PitchCar",
    yearPublished: 1995,
    players: { min: 2, max: 8, best: [4, 6] },
    playtime: { min: 30, max: 30, avg: 30 },
    age: { publisher: 6, community: 6 },
    rubric: r(20, 10, 90, 70, 12, 80, 0),
    mechanics: ["Flicking", "Modular Board"],
    categories: ["Action / Dexterity", "Racing"],
    bggRating: 7.1,
    designer: "Jean du Poël",
    description: "Flick wooden cars around a modular track. Pure skill, pure cheers.",
  },
  {
    bggId: "37111",
    name: "Battlestar Galactica",
    yearPublished: 2008,
    players: { min: 3, max: 7, best: [5, 6] },
    playtime: { min: 120, max: 240, avg: 180 },
    age: { publisher: 10, community: 14 },
    rubric: r(25, 60, 50, 90, 78, 70, 30),
    mechanics: ["Hidden Roles", "Traitor", "Cooperative Game"],
    categories: ["Bluffing", "Deduction", "Science Fiction", "Spies / Secret Agents"],
    bggRating: 7.7,
    designer: "Corey Konieczka",
    description: "There is a cylon among you. A long, paranoid classic.",
  },
  {
    bggId: "175921",
    name: "Food Chain Magnate",
    yearPublished: 2016,
    players: { min: 2, max: 5, best: [3, 4] },
    playtime: { min: 120, max: 240, avg: 180 },
    age: { publisher: 14, community: 14 },
    rubric: r(5, 95, 85, 30, 98, 80, 95),
    mechanics: ["Economic", "Worker Placement", "Network Building"],
    categories: ["Economic", "Industry / Manufacturing"],
    bggRating: 8.1,
    designer: "Jeroen Doumen, Joris Dormans",
    description: "Fast food empires. Brutal, brilliant, not for a Tuesday.",
  },
  {
    bggId: "1269",
    name: "Stockpile",
    yearPublished: 2026,
    players: { min: 2, max: 6, best: [3, 4] },
    playtime: { min: 20, max: 40, avg: 30 },
    age: { publisher: 7, community: 6 },
    rubric: r(40, 42, 38, 50, 22, 58, 32),
    mechanics: ["Hand Management", "Pattern Building"],
    categories: ["Card Game", "Children's Game"],
    bggRating: 6.2,
    designer: "GameFinder",
    description: "Empty your personal stock. Build shared piles 1 through 12. Wilds are W. Play it here.",
  },
  {
    bggId: "1258",
    name: "Phase 10",
    yearPublished: 1982,
    players: { min: 2, max: 6, best: [4] },
    playtime: { min: 45, max: 90, avg: 60 },
    age: { publisher: 7, community: 7 },
    rubric: r(48, 45, 35, 48, 28, 52, 35),
    mechanics: ["Set Collection", "Hand Management", "Shedding"],
    categories: ["Card Game"],
    bggRating: 5.3,
    designer: "Ken Johnson",
    description: "Ten phases. Sets, runs, color. Miss one and you sit there another hand.",
  },
  {
    bggId: "22664",
    name: "Phase 10 Masters Edition",
    yearPublished: 2001,
    players: { min: 2, max: 6, best: [4] },
    playtime: { min: 60, max: 90, avg: 75 },
    age: { publisher: 8, community: 8 },
    rubric: r(42, 52, 40, 45, 34, 55, 40),
    mechanics: ["Set Collection", "Hand Management", "Shedding"],
    categories: ["Card Game"],
    bggRating: 5.8,
    designer: "Ken Johnson",
    description: "Phase 10 with wilder wilds and meaner skips. Same ten-phase climb.",
  },
  {
    bggId: "38187",
    name: "Phase 10 Twist",
    yearPublished: 2007,
    players: { min: 2, max: 6, best: [4] },
    playtime: { min: 45, max: 75, avg: 55 },
    age: { publisher: 7, community: 7 },
    rubric: r(50, 40, 32, 48, 26, 50, 30),
    mechanics: ["Set Collection", "Hand Management", "Dice Rolling"],
    categories: ["Card Game"],
    bggRating: 6.1,
    designer: "Ken Johnson",
    description: "Twist cards and a spinner shuffle which phase you're chasing.",
  },
  {
    bggId: "2578",
    name: "Phase 10 Dice",
    yearPublished: 1993,
    players: { min: 2, max: 6, best: [3, 4] },
    playtime: { min: 20, max: 40, avg: 30 },
    age: { publisher: 8, community: 7 },
    rubric: r(70, 20, 25, 50, 18, 48, 10),
    mechanics: ["Dice Rolling", "Set Collection", "Push Your Luck"],
    categories: ["Dice", "Card Game"],
    bggRating: 5.4,
    designer: "Ken Johnson",
    description: "The ten phases, but you roll them. Keep or bust.",
  },
  {
    bggId: "271460",
    name: "UNO Flip!",
    yearPublished: 2019,
    players: { min: 2, max: 10, best: [4, 5] },
    playtime: { min: 15, max: 30, avg: 20 },
    age: { publisher: 7, community: 6 },
    rubric: r(78, 12, 18, 72, 16, 48, 6),
    mechanics: ["Hand Management", "Take That", "Shedding"],
    categories: ["Card Game", "Party Game"],
    bggRating: 6.4,
    designer: "Merle Robbins",
    description: "Light side, dark side. Flip the deck and Draw Five starts landing.",
  },
  {
    bggId: "2818",
    name: "UNO Attack!",
    yearPublished: 1998,
    players: { min: 2, max: 10, best: [4, 5, 6] },
    playtime: { min: 15, max: 30, avg: 20 },
    age: { publisher: 7, community: 6 },
    rubric: r(82, 8, 15, 78, 14, 45, 5),
    mechanics: ["Hand Management", "Take That", "Shedding", "Real-Time"],
    categories: ["Card Game", "Electronic", "Party Game"],
    bggRating: 5.4,
    designer: "Merle Robbins",
    description: "Hit the launcher. Sometimes nothing. Sometimes a fountain of cards.",
  },
  {
    bggId: "24318",
    name: "UNO Spin",
    yearPublished: 2005,
    players: { min: 2, max: 10, best: [4, 5] },
    playtime: { min: 20, max: 30, avg: 25 },
    age: { publisher: 7, community: 6 },
    rubric: r(80, 10, 15, 74, 16, 42, 5),
    mechanics: ["Hand Management", "Take That", "Shedding", "Dice Rolling"],
    categories: ["Card Game", "Party Game"],
    bggRating: 5.3,
    designer: "Merle Robbins",
    description: "Play a Spin card and the wheel decides who draws, discards, or trades.",
  },
  {
    bggId: "246701",
    name: "DOS",
    yearPublished: 2018,
    players: { min: 2, max: 4, best: [3, 4] },
    playtime: { min: 15, max: 30, avg: 20 },
    age: { publisher: 7, community: 7 },
    rubric: r(70, 22, 22, 60, 18, 45, 8),
    mechanics: ["Hand Management", "Shedding"],
    categories: ["Card Game"],
    bggRating: 5.1,
    designer: "Merle Robbins",
    description: "Uno's cousin with two discard piles. Number-match across both.",
  },
  {
    bggId: "386551",
    name: "DOS: Second Edition",
    yearPublished: 2022,
    players: { min: 2, max: 4, best: [3, 4] },
    playtime: { min: 15, max: 30, avg: 20 },
    age: { publisher: 7, community: 7 },
    rubric: r(68, 24, 24, 60, 18, 46, 8),
    mechanics: ["Hand Management", "Shedding"],
    categories: ["Card Game"],
    bggRating: 5.6,
    designer: "Merle Robbins",
    description: "DOS cleaned up: two piles, wilder wilds, still shout DOS.",
  },
  {
    bggId: "399088",
    name: "UNO: Show 'Em No Mercy",
    yearPublished: 2023,
    players: { min: 2, max: 8, best: [4, 5, 6] },
    playtime: { min: 15, max: 30, avg: 22 },
    age: { publisher: 7, community: 8 },
    rubric: r(72, 14, 22, 85, 18, 62, 6),
    mechanics: ["Hand Management", "Take That", "Shedding"],
    categories: ["Card Game", "Party Game"],
    bggRating: 7.0,
    designer: "Merle Robbins",
    description: "Draw 6. Skip everyone. Stacking is legal. Mercy is not.",
  },
  {
    bggId: "9090",
    name: "My First UNO",
    yearPublished: 1989,
    players: { min: 2, max: 4, best: [3, 4] },
    playtime: { min: 10, max: 15, avg: 12 },
    age: { publisher: 3, community: 3 },
    rubric: r(70, 8, 10, 55, 8, 35, 4),
    mechanics: ["Hand Management", "Shedding"],
    categories: ["Card Game", "Children's Game"],
    bggRating: 5.4,
    designer: "Merle Robbins",
    description: "Giant cards, numbers 1–7, no Reverse. Uno for the preschool table.",
  },
  {
    bggId: "352997",
    name: "UNO: All Wild!",
    yearPublished: 2022,
    players: { min: 2, max: 10, best: [4, 5] },
    playtime: { min: 10, max: 20, avg: 15 },
    age: { publisher: 7, community: 6 },
    rubric: r(88, 6, 10, 80, 10, 50, 4),
    mechanics: ["Hand Management", "Take That", "Shedding"],
    categories: ["Card Game", "Party Game"],
    bggRating: 5.8,
    designer: "Merle Robbins",
    description: "Every card is wild. The deck is a dare.",
  },
  {
    bggId: "380300",
    name: "UNO Flex!",
    yearPublished: 2023,
    players: { min: 2, max: 8, best: [4, 5] },
    playtime: { min: 15, max: 30, avg: 20 },
    age: { publisher: 7, community: 6 },
    rubric: r(74, 16, 20, 70, 16, 50, 6),
    mechanics: ["Hand Management", "Take That", "Shedding"],
    categories: ["Card Game", "Party Game"],
    bggRating: 6.2,
    designer: "Merle Robbins",
    description: "Split cards. Play one half or flex both if you can.",
  },
  {
    bggId: "343122",
    name: "UNO Triple Play",
    yearPublished: 2021,
    players: { min: 2, max: 6, best: [4] },
    playtime: { min: 15, max: 30, avg: 22 },
    age: { publisher: 7, community: 7 },
    rubric: r(70, 22, 24, 68, 20, 48, 8),
    mechanics: ["Hand Management", "Take That", "Shedding"],
    categories: ["Card Game", "Party Game"],
    bggRating: 5.9,
    designer: "Merle Robbins",
    description: "Three discard piles. Dump too many on one and the tray dumps you.",
  },
  {
    bggId: "372973",
    name: "UNO Party!",
    yearPublished: 2022,
    players: { min: 2, max: 16, best: [8, 10] },
    playtime: { min: 15, max: 40, avg: 25 },
    age: { publisher: 7, community: 7 },
    rubric: r(76, 10, 15, 88, 16, 52, 5),
    mechanics: ["Hand Management", "Take That", "Shedding"],
    categories: ["Card Game", "Party Game"],
    bggRating: 6.3,
    designer: "Merle Robbins",
    description: "Sixteen seats. Swap Hands, Skip Two, chaos at volume.",
  },
  {
    bggId: "394783",
    name: "UNO Quatro",
    yearPublished: 2023,
    players: { min: 2, max: 4, best: [2] },
    playtime: { min: 10, max: 20, avg: 15 },
    age: { publisher: 7, community: 6 },
    rubric: r(35, 40, 45, 40, 18, 50, 10),
    mechanics: ["Pattern Building", "Tile Placement"],
    categories: ["Abstract Strategy", "Card Game", "Children's Game"],
    bggRating: 5.3,
    designer: "Merle Robbins",
    description: "Connect Four with Uno tiles. Four in a row by color or number.",
  },
  {
    bggId: "172237",
    name: "UNO Dare!",
    yearPublished: 2014,
    players: { min: 2, max: 10, best: [4, 5, 6] },
    playtime: { min: 15, max: 30, avg: 20 },
    age: { publisher: 7, community: 8 },
    rubric: r(72, 8, 12, 90, 14, 48, 4),
    mechanics: ["Hand Management", "Take That", "Shedding", "Acting"],
    categories: ["Card Game", "Party Game"],
    bggRating: 5.2,
    designer: "Merle Robbins",
    description: "Play it or dare it. Draw cards, or do the thing.",
  },
  {
    bggId: "147647",
    name: "UNO Blast",
    yearPublished: 2013,
    players: { min: 2, max: 6, best: [4] },
    playtime: { min: 15, max: 25, avg: 20 },
    age: { publisher: 7, community: 6 },
    rubric: r(80, 10, 15, 72, 14, 42, 5),
    mechanics: ["Hand Management", "Take That", "Shedding", "Push Your Luck"],
    categories: ["Card Game", "Electronic", "Party Game"],
    bggRating: 5.3,
    designer: "Merle Robbins",
    description: "Can't play? Load the blaster. Someone's about to eat the deck.",
  },
  {
    bggId: "38038",
    name: "UNO Flash",
    yearPublished: 2008,
    players: { min: 2, max: 6, best: [4] },
    playtime: { min: 10, max: 20, avg: 15 },
    age: { publisher: 7, community: 6 },
    rubric: r(78, 8, 20, 75, 16, 40, 4),
    mechanics: ["Hand Management", "Shedding", "Real-Time"],
    categories: ["Card Game", "Electronic", "Party Game"],
    bggRating: 5.5,
    designer: "Merle Robbins",
    description: "Lights, timer, slap the unit. Slow hands draw.",
  },
  {
    bggId: "16693",
    name: "UNO H2O",
    yearPublished: 2004,
    players: { min: 2, max: 10, best: [4, 5] },
    playtime: { min: 15, max: 30, avg: 20 },
    age: { publisher: 7, community: 6 },
    rubric: r(75, 10, 15, 70, 12, 40, 5),
    mechanics: ["Hand Management", "Take That", "Shedding"],
    categories: ["Card Game", "Party Game"],
    bggRating: 6.0,
    designer: "Merle Robbins",
    description: "Waterproof cards. Downpour wilds. Poolside legal.",
  },
  {
    bggId: "455524",
    name: "Liar's UNO",
    yearPublished: 2025,
    players: { min: 2, max: 8, best: [4, 5, 6] },
    playtime: { min: 15, max: 30, avg: 22 },
    age: { publisher: 7, community: 8 },
    rubric: r(65, 20, 25, 88, 20, 58, 8),
    mechanics: ["Hand Management", "Bluffing", "Shedding"],
    categories: ["Card Game", "Bluffing", "Party Game"],
    bggRating: 6.0,
    designer: "Merle Robbins",
    description: "Play face-down and lie. Catch them or eat the pile.",
  },
  {
    bggId: "116593",
    name: "UNO Dice Game",
    yearPublished: 2011,
    players: { min: 2, max: 4, best: [3, 4] },
    playtime: { min: 15, max: 25, avg: 20 },
    age: { publisher: 7, community: 7 },
    rubric: r(72, 18, 22, 55, 16, 45, 6),
    mechanics: ["Dice Rolling", "Push Your Luck", "Shedding"],
    categories: ["Dice", "Card Game"],
    bggRating: 5.4,
    designer: "Merle Robbins",
    description: "Uno on dice. Color, number, draw-two — keep rolling or pass.",
  },

  {
    bggId: "204583",
    name: "Kingdomino",
    yearPublished: 2016,
    players: { min: 2, max: 4, best: [2, 4] },
    playtime: { min: 15, max: 25, avg: 20 },
    age: { publisher: 8, community: 6 },
    rubric: r(25, 45, 35, 40, 22, 78, 20),
    mechanics: ["Tile Placement", "Set Collection"],
    categories: ["Family", "Medieval"],
    bggRating: 7.3,
    designer: "Bruno Cathala",
    description: "Draft dominoes. Build a 5×5 kingdom. Crowns times terrain.",
  },
  {
    bggId: "410201",
    name: "Wyrmspan",
    yearPublished: 2024,
    players: { min: 1, max: 5, best: [2, 3] },
    playtime: { min: 75, max: 100, avg: 90 },
    age: { publisher: 14, community: 12 },
    rubric: r(30, 72, 55, 28, 58, 82, 68),
    mechanics: ["Engine Building", "Card Drafting", "Tableau Building"],
    categories: ["Animals", "Fantasy"],
    bggRating: 7.9,
    designer: "Connie Vogelmann",
    description: "Excavate caves. Entice dragons. A Wingspan cousin with bite.",
  },
  {
    bggId: "367220",
    name: "Sea Salt & Paper",
    yearPublished: 2022,
    players: { min: 2, max: 4, best: [2, 3] },
    playtime: { min: 30, max: 45, avg: 35 },
    age: { publisher: 8, community: 8 },
    rubric: r(40, 40, 35, 35, 24, 80, 18),
    mechanics: ["Set Collection", "Hand Management", "Push Your Luck"],
    categories: ["Card Game", "Animals"],
    bggRating: 7.6,
    designer: "Bruno Cathala, Théo Rivière",
    description: "Origami ocean. Call stop or keep fishing for combos.",
  },
  {
    bggId: "98778",
    name: "Hanabi",
    yearPublished: 2010,
    players: { min: 2, max: 5, best: [4] },
    playtime: { min: 25, max: 30, avg: 28 },
    age: { publisher: 8, community: 8 },
    rubric: r(20, 55, 50, 90, 32, 75, 15),
    mechanics: ["Communication Limits", "Cooperative Game", "Memory"],
    categories: ["Card Game", "Deduction"],
    bggRating: 7.1,
    designer: "Antoine Bauza",
    description: "Hold your cards out. The table sees them. You don't.",
  },
  {
    bggId: "324856",
    name: "SCOUT",
    yearPublished: 2019,
    players: { min: 2, max: 5, best: [4, 5] },
    playtime: { min: 15, max: 25, avg: 20 },
    age: { publisher: 9, community: 8 },
    rubric: r(25, 50, 45, 50, 28, 82, 12),
    mechanics: ["Hand Management", "Ladder Climbing"],
    categories: ["Card Game"],
    bggRating: 7.7,
    designer: "Kei Kanazawa",
    description: "Your hand is a circus lineup. Play runs. Never reorder — flip the whole hand.",
  },
  {
    bggId: "63268",
    name: "Spot It!",
    yearPublished: 2009,
    players: { min: 2, max: 8, best: [4, 5, 6] },
    playtime: { min: 10, max: 15, avg: 12 },
    age: { publisher: 6, community: 4 },
    rubric: r(15, 10, 80, 70, 10, 70, 4),
    mechanics: ["Pattern Recognition", "Real-Time"],
    categories: ["Children's Game", "Party Game"],
    bggRating: 6.7,
    designer: "Denis Blanchard, Guillaume Gille-Naves, Igor Polouchine",
    description: "Two cards. Exactly one match. Slap it first.",
  },
  {
    bggId: "42057",
    name: "Monopoly Deal",
    yearPublished: 2008,
    players: { min: 2, max: 5, best: [3, 4] },
    playtime: { min: 15, max: 30, avg: 22 },
    age: { publisher: 8, community: 8 },
    rubric: r(55, 30, 25, 65, 22, 62, 25),
    mechanics: ["Set Collection", "Take That", "Hand Management"],
    categories: ["Card Game", "Economic"],
    bggRating: 6.4,
    designer: "Toy Vault",
    description: "Three complete property sets. Rent cards. No board, no tears.",
  },
  {
    bggId: "41114",
    name: "Sleeping Queens",
    yearPublished: 2005,
    players: { min: 2, max: 5, best: [3, 4] },
    playtime: { min: 10, max: 20, avg: 15 },
    age: { publisher: 8, community: 5 },
    rubric: r(60, 20, 20, 55, 14, 50, 8),
    mechanics: ["Memory", "Take That", "Set Collection"],
    categories: ["Card Game", "Children's Game", "Fantasy"],
    bggRating: 6.1,
    designer: "Miranda Evarts",
    description: "Wake queens with kings. Knights steal. Dragons snore.",
  },
  {
    bggId: "412804",
    name: "Bank",
    yearPublished: 2024,
    players: { min: 2, max: 10, best: [4, 5, 6] },
    playtime: { min: 20, max: 40, avg: 30 },
    age: { publisher: 6, community: 6 },
    rubric: r(70, 18, 20, 88, 14, 72, 8),
    mechanics: ["Dice Rolling", "Push Your Luck", "Player Elimination"],
    categories: ["Dice", "Party Game", "Children's Game"],
    bggRating: 6.8,
    designer: "Thunderhive Games",
    description: "A shared pot, two dice, and one word: BANK. Don't be the 7.",
  },
];

const byId = new Map<string, Game>();
export const GAMES: Game[] = RAW.map((raw) => {
  // Unique names: the second Wonderland's War entry was a placeholder.
  if (raw.bggId === "318184") {
    raw = {
      ...raw,
      bggId: "367041",
      name: "The Guild of Merchant Explorers",
      yearPublished: 2022,
      players: { min: 1, max: 4, best: [2, 3] },
      playtime: { min: 45, max: 45, avg: 45 },
      age: { publisher: 14, community: 12 },
      rubric: r(20, 70, 50, 20, 48, 80, 55),
      mechanics: ["Map Addition", "Set Collection", "Bingo"],
      categories: ["Exploration", "Fantasy"],
      bggRating: 7.6,
      designer: "Matthew Dunstan, Brett J. Gilbert",
      description: "Explore a map four times. Routes reset; discoveries stay.",
    };
  }
  const game = g(raw);
  if (byId.has(game.bggId)) return null;
  byId.set(game.bggId, game);
  return game;
}).filter((g): g is Game => g !== null);

export function searchGames(query: string): Game[] {
  const q = query.trim().toLowerCase();
  const pool = standaloneGames();
  if (!q) return pool.slice().sort((a, b) => b.bggRating - a.bggRating);
  return pool.filter((g) => {
    const hay = `${g.name} ${g.designer} ${g.categories.join(" ")} ${g.vibes.join(" ")}`.toLowerCase();
    return hay.includes(q);
  }).sort((a, b) => b.bggRating - a.bggRating);
}

export function isStandaloneGame(game: Game): boolean {
  return /^\d+$/.test(game.bggId) && !game.categories.some((c) => /expansion/i.test(c));
}

export function standaloneGames(): Game[] {
  return GAMES.filter(isStandaloneGame);
}

export const STARTER_SHELF_IDS = [
  "178900",
  "266192",
  "9209",
  "230802",
  "30549",
  "822",
  "148228",
  "133473",
  "254640",
  "262543",
  "163412",
  "295770",
];
