/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as CircleIndexRouteImport } from './routes/circle.index'
import { Route as CircleGroupIdRouteImport } from './routes/circle.$groupId'
import { Route as GameIdRouteImport } from './routes/game.$id'
import { Route as InternalFlagsRouteImport } from './routes/internal.flags'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as PlaySessionIdRouteImport } from './routes/play.$sessionId'
import { Route as PlayBankRouteImport } from './routes/play.bank'
import { Route as PlayStockpileRouteImport } from './routes/play.stockpile'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as GameIdIndexRouteImport } from './routes/game.$id.index'
import { Route as GameIdScoreRouteImport } from './routes/game.$id.score'
import { Route as GameIdTableRouteImport } from './routes/game.$id.table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleIndexRoute = CircleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CircleRoute,
} as any)
const CircleGroupIdRoute = CircleGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => CircleRoute,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalFlagsRoute = InternalFlagsRouteImport.update({
  id: '/internal/flags',
  path: '/internal/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySessionIdRoute = PlaySessionIdRouteImport.update({
  id: '/play/$sessionId',
  path: '/play/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayBankRoute = PlayBankRouteImport.update({
  id: '/play/bank',
  path: '/play/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayStockpileRoute = PlayStockpileRouteImport.update({
  id: '/play/stockpile',
  path: '/play/stockpile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdIndexRoute = GameIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameIdRoute,
} as any)
const GameIdScoreRoute = GameIdScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => GameIdRoute,
} as any)
const GameIdTableRoute = GameIdTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => GameIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circle': typeof CircleRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/scoreboard': typeof ScoreboardRoute
  '/vault': typeof VaultRoute
  '/wizard': typeof WizardRoute
  '/circle/$groupId': typeof CircleGroupIdRoute
  '/game/$id': typeof GameIdRouteWithChildren
  '/internal/flags': typeof InternalFlagsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/play/bank': typeof PlayBankRoute
  '/play/stockpile': typeof PlayStockpileRoute
  '/circle/': typeof CircleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/game/$id/score': typeof GameIdScoreRoute
  '/game/$id/table': typeof GameIdTableRoute
  '/game/$id/': typeof GameIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/scoreboard': typeof ScoreboardRoute
  '/vault': typeof VaultRoute
  '/wizard': typeof WizardRoute
  '/circle/$groupId': typeof CircleGroupIdRoute
  '/internal/flags': typeof InternalFlagsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/play/bank': typeof PlayBankRoute
  '/play/stockpile': typeof PlayStockpileRoute
  '/circle': typeof CircleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/game/$id/score': typeof GameIdScoreRoute
  '/game/$id/table': typeof GameIdTableRoute
  '/game/$id': typeof GameIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circle': typeof CircleRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/scoreboard': typeof ScoreboardRoute
  '/vault': typeof VaultRoute
  '/wizard': typeof WizardRoute
  '/circle/$groupId': typeof CircleGroupIdRoute
  '/game/$id': typeof GameIdRouteWithChildren
  '/internal/flags': typeof InternalFlagsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/play/bank': typeof PlayBankRoute
  '/play/stockpile': typeof PlayStockpileRoute
  '/circle/': typeof CircleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/game/$id/score': typeof GameIdScoreRoute
  '/game/$id/table': typeof GameIdTableRoute
  '/game/$id/': typeof GameIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/circle'
    | '/discover'
    | '/login'
    | '/profile'
    | '/results'
    | '/scoreboard'
    | '/vault'
    | '/wizard'
    | '/circle/$groupId'
    | '/game/$id'
    | '/internal/flags'
    | '/invite/$token'
    | '/play/$sessionId'
    | '/play/bank'
    | '/play/stockpile'
    | '/circle/'
    | '/api/auth/$'
    | '/game/$id/score'
    | '/game/$id/table'
    | '/game/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/login'
    | '/profile'
    | '/results'
    | '/scoreboard'
    | '/vault'
    | '/wizard'
    | '/circle/$groupId'
    | '/internal/flags'
    | '/invite/$token'
    | '/play/$sessionId'
    | '/play/bank'
    | '/play/stockpile'
    | '/circle'
    | '/api/auth/$'
    | '/game/$id/score'
    | '/game/$id/table'
    | '/game/$id'
  id:
    | '__root__'
    | '/'
    | '/circle'
    | '/discover'
    | '/login'
    | '/profile'
    | '/results'
    | '/scoreboard'
    | '/vault'
    | '/wizard'
    | '/circle/$groupId'
    | '/game/$id'
    | '/internal/flags'
    | '/invite/$token'
    | '/play/$sessionId'
    | '/play/bank'
    | '/play/stockpile'
    | '/circle/'
    | '/api/auth/$'
    | '/game/$id/score'
    | '/game/$id/table'
    | '/game/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircleRoute: typeof CircleRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResultsRoute: typeof ResultsRoute
  ScoreboardRoute: typeof ScoreboardRoute
  VaultRoute: typeof VaultRoute
  WizardRoute: typeof WizardRoute
  GameIdRoute: typeof GameIdRouteWithChildren
  InternalFlagsRoute: typeof InternalFlagsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PlaySessionIdRoute: typeof PlaySessionIdRoute
  PlayBankRoute: typeof PlayBankRoute
  PlayStockpileRoute: typeof PlayStockpileRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle/': {
      id: '/circle/'
      path: '/'
      fullPath: '/circle/'
      preLoaderRoute: typeof CircleIndexRouteImport
      parentRoute: typeof CircleRoute
    }
    '/circle/$groupId': {
      id: '/circle/$groupId'
      path: '/$groupId'
      fullPath: '/circle/$groupId'
      preLoaderRoute: typeof CircleGroupIdRouteImport
      parentRoute: typeof CircleRoute
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/flags': {
      id: '/internal/flags'
      path: '/internal/flags'
      fullPath: '/internal/flags'
      preLoaderRoute: typeof InternalFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$sessionId': {
      id: '/play/$sessionId'
      path: '/play/$sessionId'
      fullPath: '/play/$sessionId'
      preLoaderRoute: typeof PlaySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/bank': {
      id: '/play/bank'
      path: '/play/bank'
      fullPath: '/play/bank'
      preLoaderRoute: typeof PlayBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/stockpile': {
      id: '/play/stockpile'
      path: '/play/stockpile'
      fullPath: '/play/stockpile'
      preLoaderRoute: typeof PlayStockpileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id/': {
      id: '/game/$id/'
      path: '/'
      fullPath: '/game/$id/'
      preLoaderRoute: typeof GameIdIndexRouteImport
      parentRoute: typeof GameIdRoute
    }
    '/game/$id/score': {
      id: '/game/$id/score'
      path: '/score'
      fullPath: '/game/$id/score'
      preLoaderRoute: typeof GameIdScoreRouteImport
      parentRoute: typeof GameIdRoute
    }
    '/game/$id/table': {
      id: '/game/$id/table'
      path: '/table'
      fullPath: '/game/$id/table'
      preLoaderRoute: typeof GameIdTableRouteImport
      parentRoute: typeof GameIdRoute
    }
  }
}

interface CircleRouteChildren {
  CircleGroupIdRoute: typeof CircleGroupIdRoute
  CircleIndexRoute: typeof CircleIndexRoute
}

const CircleRouteChildren: CircleRouteChildren = {
  CircleGroupIdRoute: CircleGroupIdRoute,
  CircleIndexRoute: CircleIndexRoute,
}

const CircleRouteWithChildren =
  CircleRoute._addFileChildren(CircleRouteChildren)

interface GameIdRouteChildren {
  GameIdScoreRoute: typeof GameIdScoreRoute
  GameIdTableRoute: typeof GameIdTableRoute
  GameIdIndexRoute: typeof GameIdIndexRoute
}

const GameIdRouteChildren: GameIdRouteChildren = {
  GameIdScoreRoute: GameIdScoreRoute,
  GameIdTableRoute: GameIdTableRoute,
  GameIdIndexRoute: GameIdIndexRoute,
}

const GameIdRouteWithChildren =
  GameIdRoute._addFileChildren(GameIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircleRoute: CircleRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResultsRoute: ResultsRoute,
  ScoreboardRoute: ScoreboardRoute,
  VaultRoute: VaultRoute,
  WizardRoute: WizardRoute,
  GameIdRoute: GameIdRouteWithChildren,
  InternalFlagsRoute: InternalFlagsRoute,
  InviteTokenRoute: InviteTokenRoute,
  PlaySessionIdRoute: PlaySessionIdRoute,
  PlayBankRoute: PlayBankRoute,
  PlayStockpileRoute: PlayStockpileRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
